server:
  port: 8761

spring:
  application:
    name: HelloWorld



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
    service-url:
      default-zone: http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}