server:
  port: 8762

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: HelloWorld
          uri: http://localhost:8761/
          predicates:
            - Path=/second/**
        - id: CrudOperations
          uri: http://localhost:8760/
          predicates:
            - Path=/crud/**
