spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/crudoperations
    username: root
    password: 1234
  application:
    name:
      CrudOperations

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
    service-url:
      default-zone: http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8760