server:
  port: 9192

spring:
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    config:
      uri:
        - http://localhost:9196S

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: ORDER-SERVICE
